### PR TITLE
Issue #89 Resolved FAQ clickability working properly

### PR DESCRIPTION
**Pull request by Rahul-Palahwat**
### Related Issue
- Issue number goes here: #89 

### Proposed Changes 
- Toggling when clicking on arrow or question both

### Checklist 
- [x] Documentation of the code 
- [x] Add your name to the CONTRIBUTORS file 
- [x] Testing your code in the local machine 

### Screenshots
 
Can be opened when clicked anywhere on the question and same for close
Screenshot 2022-10-05 at 6 26 29 PM
Screenshot 2022-10-05 at 6 26 49 PM

### CODE REVIEW

**Comment by Rahul-Palahwat** [comment]
Hey @girlscript-asansol please review this PR..

**Comment by jay-io** [comment]
@Rahul-Palahwat The deployment preview shows otherwise. Can you check? Also, I think this feature breaks the smooth animation. Can you try to do something about it?

**Comment by Rahul-Palahwat** [comment]
ohk @jay-io on it..

**Comment by Rahul-Palahwat** [comment]
@jay-io , @girlscript-asansol review this PR

**Comment by soumali28** [comment]
@Rahul-Palahwat Looks good, Thanks for your valuable contribution.

**Review by soumali28 — APPROVED** [review]

**Pull request merged**
