### PR TITLE
Remove pre-loader scroll

### PR DESCRIPTION
**Pull request by Joshua-Nweze**
### Proposed Changes 
- Set display to "none" while pre-loader is loading and to "block" after pre-loader is done loading 

### Checklist 
- [ ] Documentation of the code 
- [ ] Add your name to the CONTRIBUTORS file 
- [ ] Testing your code in the local machine

### CODE REVIEW

**Comment by Joshua-Nweze** [comment]
You're welcome

**Review by Debdeep1 — CHANGES_REQUESTED** [review]
Hey @Joshua-Nweze ! Thanks for the PR, but am afraid you have been working on an older version. Please update you cloned repo by pulling/fetching the latest changes...otherwise these changes will conflict with the new ones and we might lose on the progress made so far.
Update your branch to the latest version and then create the PR. This will resolve a major issue. Thanks, awaiting your updated PR.

**Comment by jay-io** [comment]
@Joshua-Nweze Just realised, you were a first-time contributor. If you need help with the process, you're most welcome to join our Discord and we'll happily demonstrate in front of you.

**Comment by Joshua-Nweze** [comment]
@Debdeep1 Thanks for the info, I'll do that right away

**Comment by Joshua-Nweze** [comment]
@Debdeep1 I updated the cloned repo, made changes and created a new PR. Please check it

**Pull request closed without merging**
