### PR TITLE
Changes in Past event.

### PR DESCRIPTION
**Pull request by Sahilbal**
### Related Issue
- #72 

### Proposed Changes 
-index.html file is added.
-styles.css file is added.
-images are added.

### Checklist 
- [x] Documentation of the code 
- [x] Add your name to the CONTRIBUTORS file 
- [x] Testing your code in the local machine 

### Screenshots
 
Capture 2

### CODE REVIEW

**Comment by girlscript-asansol** [comment]
@Sahilbal check the main index.html and styles.css file we have already migrated the preloader to it. Canyou make your chnages there.

**Comment by Sahilbal** [comment]
> @Sahilbal check the main index.html and styles.css file we have already migrated the past event section to it. Canyou make your chnages there.

I am beginner to open source I don't know how to migrate to main index.html.... can you please guide me.

**Comment by girlscript-asansol** [comment]
@Sahilbal its already done see the index.html file

**Comment by Sahilbal** [comment]
> @Sahilbal its already done see the index.html file
 what to do next ?

**Comment by girlscript-asansol** [comment]
> > @Sahilbal its already done see the index.html file
> > what to do next ?
check the discord

**Review by girlscript-asansol — APPROVED** [review]

**Pull request closed without merging**
