### PR TITLE
Custom scrollbar

### PR DESCRIPTION
**Pull request by modiniraj09**
### Related Issue
- #43 

### Proposed Changes 
- Created Custom ScrollBar with hover effeccts

### Checklist 
- [X] Documentation of the code 
- [X] Add your name to the CONTRIBUTORS file 
- [X] Testing your code in the local machine 

### Screenshots
 
Screenshot 1

### CODE REVIEW

**Review by jay-io — CHANGES_REQUESTED** [review]
Could you change the scroll-bar thickness to 3px, make it rectangular, and make the white track transparent?

**Comment by modiniraj09** [comment]
> Could you change the scroll-bar thickness to 3px, make it rectangular, and make the white track transparent?

@jay-io By transparent track what do you mean?
Below two screenshots are attached, please select 1 to commit or anything else to change please specify too
pre 1
post 2

**Comment by soumali28** [comment]
2nd one looks good.

**Review by jay-io — APPROVED** [review]
@modiniraj09  Yes, thank you. I meant to say like in the second screenshot.

**Pull request merged**
