### PR TITLE
revamped "past events" section

### PR DESCRIPTION
**Pull request by KeneePatel**
### Related Issue
- Issue number goes here:

### Proposed Changes
- added two files swiper-bundle.min.css and swiper-bundle.min.js for swiper functionality
- added my info in CONTRIBUTORS
- and rest of the changes are for revamp

### Checklist
- [x] Documentation of the code 
- [x] Add your name to the CONTRIBUTORS file 
- [x] Testing your code in the local machine 

### Screenshots
Before
Before the changes

After
After the changes

### CODE REVIEW

**Comment by KeneePatel** [comment]
forgot to mention the issue associated with this. #158 , So tagging the issue here.

**Comment by Debdeep1** [comment]
> forgot to mention the issue associated with this. #158 , So tagging the issue here.

The site isnt responsive for mobile view...please have a look at that...

**Review by Debdeep1 — CHANGES_REQUESTED** [review]
Please fix the mobile view of the site....

**Comment by jay-io** [comment]
@KeneePatel Looks great but I think the desktop cards aren't hidden in mobile view. Can you check? Could you also add some padding to the mobile view cards?

Optional:
The location of the slider arrows in mobile view seems unstable. We'll have another issue for this one if you like.

**Comment by KeneePatel** [comment]
Can you give me some direction on how would I be able to make the cards hidden in mobile view? Like in the site as of now, when we change to mobile view, It pretty much hides the text and shows one image per view. Am I supposed to do the same and if yes, can you give some specific references on where to look.

**Comment by soumali28** [comment]
@KeneePatel just add a class name desktop-events in your main div (starting of the past events) it will work.

**Comment by KeneePatel** [comment]
Ayy thanks for the direction @soumali28. I did as you said and have requested a re-review.

**Review by Debdeep1 — APPROVED** [review]

**Pull request merged**
