### PR TITLE
Button width to auto and updated 'Our Programs' description

### PR DESCRIPTION
**Pull request by KeneePatel**
### Proposed Changes
- Width styling element of the "Check our Social Button"

### Checklist
- [x] Documentation of the code 
- [x] Add your name to the CONTRIBUTORS file 
- [x] Testing your code in the local machine 

### Screenshots
image
This is how it looked like before the change

image
After the change.

### CODE REVIEW

**Comment by KeneePatel** [comment]
I am sorry if it's nothing big and bothered you, but it just really triggered my OCD lol.

**Comment by KeneePatel** [comment]
I also added the pr for issue #212

**Comment by jay-io** [comment]
@KeneePatel Haha no worries, we'll merge this.

**Comment by girlscript-asansol** [comment]
@KeneePatel did you mentioned your name in the contributors file? If not please make a seperate pr for it.

**Comment by KeneePatel** [comment]
> @KeneePatel did you mentioned your name in the contributors file? If not please make a seperate pr for it.

Don't worry, I have already done that

**Pull request merged**
