### PR TITLE
Navbar added

### PR DESCRIPTION
**Pull request by LalitChauhan27**
### Related Issue
- Create a Navbar #6

### Proposed Changes
- Logo for navbar added
- Menu items for navbar added

### Checklist
- [x] Documentation of the code
- [x] Add your name to the CONTRIBUTORS file 
- [x] Testing your code in the local machine

### CODE REVIEW

**Comment by soumali28** [comment]
@LalitChauhan27 you aren't  assigned  to this issue. We need to assign the issues first and then make the PR.

**Comment by LalitChauhan27** [comment]
@soumali28 assign me this issue. So, I can help.

**Comment by jay-io** [comment]
@LalitChauhan27 Thank you for the hard work. I suppose this is your first time contributing. I'm sorry but that's not how issue threads work. You have to be assigned first before you start working on the PR. You may join our Discord and wait for more relevant issues to pop up, or suggest your own. You are advised to stay in touch or you might lose an opportunity.

**Comment by LalitChauhan27** [comment]
@jay-io Okay, thanks for the help.

**Pull request closed without merging**
