### PR TITLE
Revamp Navbar

### PR DESCRIPTION
**Pull request by theanimator20**
### Related Issue
- Issue number goes here: #128 

### Proposed Changes 
- Change 1:changed the font-weight in the anchor tag
- Change 2:changed the hover Effect in Navbar anchor tags
- Change 3: The most important one added social media icons with a dropdown menu along with making them responsive

### Checklist 
- [ x] Documentation of the code 
- [ x] Add your name to the CONTRIBUTORS file 
- [x
girlscript op
 ] Testing your code in the local machine

### CODE REVIEW

**Comment by theanimator20** [comment]
Hello i have done necessary changes  and kindly revert back if any changes else accept the merge request.

Thank You

**Comment by jay-io** [comment]
@theanimator20 Sorry for the delay. We've been a little busy. We'll review and merge it by midnight.

**Review by Debdeep1 — CHANGES_REQUESTED** [review]
I think the navbar in the mobile view will require a lot of adjustments. The alignment is off at places. Do you wanna try this again? Or you can always let us reassign this to someone else.

**Comment by theanimator20** [comment]
Yh i can work on it just tell me how u want the adjustments  in mobile view

**Comment by jay-io** [comment]
## Desktop view:
- GSA icon is way too shifted towards the left. You could provide some padding.
- The Navbar hyperlinks look way too faded, increase the opacity a little bit maybe? Could we also have a smooth transition to bright, and the way back?
- The dark/light theme button would look better aligned to the right end.
- Can you make the dropdown look simpler? I'm attaching a sample. All that the dropdown rows should contain are the social media icons and the service handles.

Sample

## Mobile view:
- You could try to make this tray change colour depending on the theme chosen. This could be optional tho. However, try aligning the logos properly one after the other with top and bottom padding for the first and the last element in the list respectively. Also try adding some corner radius.

<p align="center"></p>

- The same issue with the faded font fill. Also, the items are aligned to the right.

<p align="center"></p>

**Review by jay-io — CHANGES_REQUESTED** [review]
@theanimator20

**Comment by theanimator20** [comment]
Ok i will work on it but the  light/theme button is at top-right only na?. Also for social link I'll remove the margin-top and make it kind of similar to that

**Comment by theanimator20** [comment]
Can u elaborate more on this statement:-
All that the dropdown rows should contain are the social media icons and the service handles.
Like u'll want to add ur social handles id and not the name as such like instagram?

**Comment by theanimator20** [comment]
@jay-io  i have worked on the issues u asked for do check it out

**Comment by jay-io** [comment]
Screenshot (16)

@theanimator20 I'm not certain about mobile view tho. Can you still try to correct the overlaps and right shift?

**Comment by theanimator20** [comment]
@jay-io  is it possible to accept the PR WHATEVER I worked till now since i have other projects as well to work on and handle this work to others?.

**Comment by jay-io** [comment]
@theanimator20 We really appreciate your efforts and that's not all. We also love your follow-us mobile-view-only sidebar.

Can you revert all the changes you did on the nav panel? We'll have someone else look into it. A few other contributors approached us and they wish to give it a shot.

If you can still do it, you're most welcome to try and seek help in our server. If it's been tiresome for you, I'm afraid we can't merge a PR that kinda breaks stuff, just to help contributors win their T-shirts. We have milestones to reach, too. 

It's your call now.

**Comment by theanimator20** [comment]
Ok i will try to work on overlapping issue if u need other changes do let me know once again

**Comment by jay-io** [comment]
Ah, yes the slight right-shift that the mobile navbar options have got. If you compare what we have currently deployed on our main branch and your mobile navbar, you'll know exactly what I'm talking about. 

Btw, glow effect is nice too, see if you can preserve it.

**Comment by theanimator20** [comment]
Okay i would work on it

**Comment by theanimator20** [comment]
@jay-io  changes  Resolved Check.
mop

**Review by soumali28 — APPROVED** [review]

**Comment by jay-io** [comment]
Looks great now, thank you for contributing!

**Comment by theanimator20** [comment]
@jay-io  Thanks for having me  here  and i learned alot of  new things and also  thanks for Guiding  Me.
**Happy coding!!**

**Pull request merged**
