### PR TITLE
navbar is mobile responsive now

### PR DESCRIPTION
**Pull request by LalitChauhan27**
### Related Issue
- Make the Navbar Mobile responsive. #31

### Proposed Changes
- navbar is now responsive for all devices
- toggle bar is added for small screens
- brand name is in one line instead of 2 seperate lines
- added a gap between the logo and the brandname

### Checklist
- [x] Documentation of the code 
- [x] Add your name to the CONTRIBUTORS file 
- [x] Testing your code in the local machine 

### Screenshots
P1
P2

### CODE REVIEW

**Comment by girlscript-asansol** [comment]
@LalitChauhan27  For mobile view, brandname should be displayed beside the logo..not under it...other than that rest is ok.

**Review by Debdeep1 — APPROVED** [review]

**Review by girlscript-asansol — APPROVED** [review]

**Review by girlscript-asansol — APPROVED** [review]

**Review by Debdeep1 — CHANGES_REQUESTED** [review]
@LalitChauhan27 you  need to display brandname beside the logo and not under it. Also do change the color of toggle button to black. Other than that..the functionality is fine.

**Comment by LalitChauhan27** [comment]
@Debdeep1 @girlscript-asansol Hey, I have made the changes that you have mentioned. Please review my latest commit.
P3
P4

**Comment by LalitChauhan27** [comment]
> @LalitChauhan27 you need to display brandname beside the logo and not under it. Also do change the color of toggle button to black. Other than that..the functionality is fine.

Hey @Debdeep1, I have made the changes that you have mentioned.

**Review by Debdeep1 — APPROVED** [review]

**Pull request merged**
