### PR TITLE
modified about us section

### PR DESCRIPTION
**Pull request by savi001**
### Related Issue
- Issue number goes here: #201 

### Proposed Changes 
- changed image of about us section
- changed content of about us section
- chaned hover effect of socials as join us button

### Checklist 
- [ ] Documentation of the code 
- [x ] Add your name to the CONTRIBUTORS file 
- [x] Testing your code in the local machine 

### Screenshots
 
Screenshot 2022-10-17 at 1 34 43 AM

### CODE REVIEW

**Comment by jay-io** [comment]
Can you add a 30px bottom margin for the `aboutus-image-container` class in mobile view?

**Comment by jay-io** [comment]
A few more things:
- Add your name/username to the contributors' file
- Seems like the DSA article has its line-endings changed. Go through [these steps](https://github.com/gsasansol/GirlScript-Asansol/pull/145#pullrequestreview-1135201578) to revert your changes.

**Review by jay-io — CHANGES_REQUESTED** [review]
We'll merge your PR after these changes.

**Comment by savi001** [comment]
i think, i should also add some bottom margin margin in tablet view also , can i proceed ?

**Comment by savi001** [comment]
@jay-io i think, i should also add some bottom margin margin in tablet view also , can i proceed ?

**Comment by savi001** [comment]
I have added and changed as per your requirement

**Comment by jay-io** [comment]
@savi001 Sure. You did great, thank you for contributing!

**Review by jay-io — APPROVED** [review]

**Pull request merged**
